worker_processes 1;
error_log /dev/stderr warn;
pid /run/nginx.pid;

events {
    worker_connections 64;
}

http {
    access_log /dev/stdout;
    default_type text/html;
    server_tokens off;

    server {
        listen 8099;
        server_name _;

        # 仅允许 Supervisor 的 ingress 代理访问
        allow 172.30.32.2;
        deny all;

        root /usr/share/nginx/html;
        index index.html;

        location / {
            try_files $uri $uri/ =404;
        }
    }
}
